name: Build

on:
  pull_request:
  merge_group:
    types: [checks_requested]
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
#  lint:
#    name: ktlint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Run ktlint
#        run: |
#          ./gradlew lintKotlinMain lintKotlinTest

#  unit_tests:
#    needs: [lint]
#    runs-on: [ ubuntu-latest ]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          gradle-version: wrapper
#
#      - name: Add google-services.json
#        run: echo $GOOGLE_SERVICES >> app/google-services.json
#        env:
#          GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES_JSON}}
#
#      - name: Run unit tests
#        run: |
#          ./gradlew assembleHermioneDebug
#          ./gradlew testHermioneDebugUnitTest

  build:
    runs-on: [ubuntu-latest]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

#      - name: Add google-services.json
#        run: echo $GOOGLE_SERVICES >> app/google-services.json
#        env:
#          GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES_JSON}}

      - name: Clean build artifacts
        run: ./gradlew clean

      - name: Build release APK (as check because I don't have any tests yet)
        env:
          WP_CLIENT_ID : ${{ secrets.WP_CLIENT_ID }}
          WP_CLIENT_SECRET : ${{ secrets.WP_CLIENT_SECRET }}
        run: ./gradlew :app:assembleGrannyRelease