name: Create PR when dependency graphs change

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v3

      - name: Generate graphs
        run: ./gradlew dependencyGraph
        if: success()

      # Get changed files list and set them to `outputs.changed`
      - id: get-pr-body
        run: |
          ./.github/scripts/changed_files.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            dependencyGraph.md
            **/dependencyGraph.md
          commit-message: Updated dependency graphs
          branch: updated-dependency-graphs
          delete-branch: true
          title: Updated dependency graphs
          body: |
            ## Description
            Dependency graphs have been updated.

            List of changed files:
            ${{steps.get-pr-body.outputs.changed}}
